app:
  name: "Reverse Coding : Code Runner"
  
  # app behavior 
  port : 8080

  # configurations related to codes to run
  code_directory: "codes"
  
  # link seeding endpoint
  seed_source: https://rc-broadcaster.vercel.app/api/app.js