name: Build package
on: [push, pull_request]
jobs:
  build:
    name: Golang Binary Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build for unix systems
        run: make pack_unix

      - name: Build for windows systems
        run: make pack_win

      - name: Publish UNIX Build
        uses: actions/upload-artifact@v2
        with:
          name: task-runner-unix
          path: build/task-runner

      - name: Publish Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: task-runner-windows
          path: build/task-runner.exe

  docker-build-push:
    name: Docker build, publish as yashkumarverma/rc-task-runner
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch build artifact
        uses: actions/download-artifact@v2
        with:
          name: task-runner-unix
      
      - name: Prepare for build
        run: |
          mkdir build
          mv task-runner build/task-runner 
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: yashkumarverma/rc-task-runner:latest
          push: true
